version: '3'

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres

  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - PYTHONDONTWRITEBYTECODE=1
    build:
      context: ./
      args:
        - BUILD_COMMIT_SHA=localdev
    command: python wait_for_postgres.py && pip install -r requirements.txt &&
             ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
