version: '3'

services:
  mysql:
    image: mariadb:10
    restart: always
    env_file:
      - localdev.env
    volumes:
      - esdkp-mysql:/var/lib/mysql
      - ./local-init.sql:/docker-entrypoint-initdb.d/local-init.sql

  web:
    restart: always
    env_file:
      - localdev.env
    build:
      context: ./
      args:
        - BUILD_COMMIT_SHA=localdev
    command: >-
      /bin/bash -c "pip install --user -r requirements.txt &&
      /wait &&
      ./manage.py migrate &&
      ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    depends_on:
      - mysql

volumes:
  esdkp-mysql: