# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expansion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("short_name", models.TextField(unique=True)),
            ],
            options={"verbose_name": "Expansion", "verbose_name_plural": "Expansions"},
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "expansion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eq.Expansion"
                    ),
                ),
            ],
            options={"verbose_name": "Flag", "verbose_name_plural": "Flags"},
        ),
        migrations.CreateModel(
            name="Klass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("short_name", models.TextField(unique=True)),
            ],
            options={"verbose_name": "Class", "verbose_name_plural": "Classes"},
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("short_name", models.TextField(unique=True)),
            ],
            options={"verbose_name": "Race", "verbose_name_plural": "Races"},
        ),
    ]
