# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('surname', models.TextField(blank=True)),
                ('eqclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eq.Klass')),
                ('eqflags', models.ManyToManyField(blank=True, to='eq.Flag')),
                ('eqrace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eq.Race')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('short_name', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='guild',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eq.Server'),
        ),
        migrations.AddField(
            model_name='character',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eq.Guild'),
        ),
    ]
