# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-08 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eq', '0002_auto_20170407_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='guild',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eq.Guild'),
        ),
    ]
