# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("eq", "0004_auto_20170408_0109")]

    operations = [
        migrations.AddField(
            model_name="character",
            name="server",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="eq.Server"
            ),
            preserve_default=False,
        )
    ]
