# Generated by Django 2.0.1 on 2018-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eq", "0006_event_item")]

    operations = [
        migrations.AddField(
            model_name="item", name="default_value", field=models.FloatField(default=0)
        )
    ]
