# Generated by Django 2.0.1 on 2018-05-02 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("eq", "0007_item_default_value")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="expansion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eq.Expansion",
            ),
        )
    ]
