# Generated by Django 2.0.1 on 2018-05-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("eq", "0008_auto_20180502_2335")]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="default_value", new_name="dkp"
        )
    ]
