# Generated by Django 3.0.7 on 2020-07-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eq", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("characters", models.ManyToManyField(blank=True, to="eq.Character")),
            ],
            options={"verbose_name": "Person", "verbose_name_plural": "People",},
        ),
    ]
