# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("eq", "0002_auto_20170407_1716"), ("roster", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("characters", models.ManyToManyField(blank=True, to="eq.Character")),
            ],
            options={"verbose_name": "Person", "verbose_name_plural": "People"},
        ),
        migrations.RemoveField(model_name="eqcharacter", name="eqclass"),
        migrations.RemoveField(model_name="eqcharacter", name="eqflags"),
        migrations.RemoveField(model_name="eqcharacter", name="eqrace"),
        migrations.DeleteModel(name="EQCharacter"),
    ]
