# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_auto_20141022_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqcharacter',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='eqclass',
            name='short_name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='eqexpansion',
            name='short_name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='eqrace',
            name='short_name',
            field=models.TextField(unique=True),
        ),
    ]
