# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_auto_20161031_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqcharacter',
            name='flags',
            field=models.ManyToManyField(blank=True, to='roster.EQFlag'),
        ),
    ]
