# Generated by Django 3.0.7 on 2020-07-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eq", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dkp", models.FloatField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eq.Character",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eq.Item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Raid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("attendance_value", models.FloatField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eq.Event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Raider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eq.Character"
                    ),
                ),
                ("loot", models.ManyToManyField(to="dkp.Loot")),
                (
                    "raid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dkp.Raid"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="loot",
            name="raid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dkp.Raid"
            ),
        ),
    ]
