# Generated by Django 3.0.14 on 2022-05-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raider',
            name='loot',
            field=models.ManyToManyField(blank=True, to='dkp.Loot'),
        ),
    ]
