# Generated by Django 2.0.1 on 2018-08-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dkp", "0004_raider")]

    operations = [
        migrations.AlterField(model_name="raid", name="date", field=models.DateField())
    ]
